# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff128bebe9b1fc1b5aef10204b383ea5aab138898a2a0c7c986b9969f77944ce975ba5e55e7bd7e9d9e0747825d261aabb8853df9bf8295924c1af2cea238a96

test:
  secret_key_base: 101b0711a546e99320720987ab733a0cd9208c5e39ff688144f8b3042b68fced6a588b19f07d0290413437122a964620faf5158a9f7d159acb5f6d7c334354ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
